### PR TITLE
Update Hessian2Output.java

### PR DESCRIPTION
**Pull request by qingkaiyan**
3.2.13 and older version had this

### CODE REVIEW

**Comment by AlbumenJ** [comment]
https://github.com/ebourg/hessian/blob/c7b2bf485af95bc507e420a7c185db45eff8f3ed/src/com/caucho/hessian/io/Hessian2Output.java#L1162

**Comment by AlbumenJ** [comment]
Why should flush here

**Comment by qingkaiyan** [comment]
I update dubbo application from 3.2.13 to 3.3.0-beta4.
Other older dubbo application appear hessian2 deserialize expcetion.
It is seems flush() or some other plance case backward compatible 

`2024-07-05 08:05:35.988 trace_id=e7037e0d4ed2a4c06b08a42319594744 span_id=68635d57e9a31881 trace_flags=01 [DubboServerHandler-[10.12.122.175:13106](http://10.12.122.175:13106/)-thread-5883] ERROR c.s.t.a.f.DefaultConsumerFilter - 接口报错:Failed to invoke remote method: getComplainListByApp, provider: dubbo://[10.8.81.135:13114/com.sprucetec.tms.integral.complain.service.ComplainAppService?application=tms-app-service&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&environment=prod&generic=false&group=complainService&id=tms-app-service&init=false&interface=com.sprucetec.tms.integral.complain.service.ComplainAppService&metadata-type=remote&methods=appealOp,getComplainDetail,getComplainListByApp,getComplainListCount&organization=dubbox&owner=programmer&pid=163565&prefer.serialization=kryo,hessian2&reference.filter=default,defaultConsumerFilter&register.ip=10.12.122.175&release=3.3.0-beta.4&remote.application=tms-integral-main&retries=0&revision=1.1.6&serialization=hessian2&serialize.check.status=WARN&service-name-mapping=true&service.filter=default&side=consumer&sticky=false&timeout=3000&timestamp=1720083485684&triple.enable.push=false&triple.header.table.size=4096&triple.initial.buffer.size=16384&triple.initial.window.size=8388608&triple.max.body.size=8388608&triple.max.chunk.size=8388608&triple.max.concurrent.streams=2147483647&triple.max.frame.size=8388608&triple.max.header.list.size=32768&triple.max.header.size=8192&triple.max.initial.line.length=4096&triple.max.response.body.size=8388608&version=*](http://10.8.81.135:13114/com.sprucetec.tms.integral.complain.service.ComplainAppService?application=tms-app-service&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&environment=prod&generic=false&group=complainService&id=tms-app-service&init=false&interface=com.sprucetec.tms.integral.complain.service.ComplainAppService&metadata-type=remote&methods=appealOp,getComplainDetail,getComplainListByApp,getComplainListCount&organization=dubbox&owner=programmer&pid=163565&prefer.serialization=kryo,hessian2&reference.filter=default,defaultConsumerFilter&register.ip=10.12.122.175&release=3.3.0-beta.4&remote.application=tms-integral-main&retries=0&revision=1.1.6&serialization=hessian2&serialize.check.status=WARN&service-name-mapping=true&service.filter=default&side=consumer&sticky=false&timeout=3000&timestamp=1720083485684&triple.enable.push=false&triple.header.table.size=4096&triple.initial.buffer.size=16384&triple.initial.window.size=8388608&triple.max.body.size=8388608&triple.max.chunk.size=8388608&triple.max.concurrent.streams=2147483647&triple.max.frame.size=8388608&triple.max.header.list.size=32768&triple.max.header.size=8192&triple.max.initial.line.length=4096&triple.max.response.body.size=8388608&version=*), cause: org.apache.dubbo.remoting.RemotingException: com.alibaba.com.caucho.hessian.io.HessianFieldException: com.sprucetec.tms.integral.app.dto.ComplainDto.appealType: java.lang.Byte cannot be assigned from null
com.alibaba.com.caucho.hessian.io.HessianFieldException: com.sprucetec.tms.integral.app.dto.ComplainDto.appealType: java.lang.Byte cannot be assigned from null
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.logDeserializeError(JavaDeserializer.java:174)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:415)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:277)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:204)
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.readObject(SerializerFactory.java:548)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2850)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2773)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2308)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2747)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2308)
	at com.alibaba.com.caucho.hessian.io.CollectionDeserializer.readLengthList(CollectionDeserializer.java:124)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2722)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2308)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2110)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:411)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:277)
	at com.alibaba.com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:204)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2848)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2175)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2148)
	at com.alibaba.com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2104)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:102)
	at org.apache.dubbo.common.serialize.hessian2.Hessian2ObjectInput.readObject(Hessian2ObjectInput.java:107)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.handleValue(DecodeableRpcResult.java:157)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:101)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:129)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:48)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:196)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:99)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:179)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:61)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at com.sprucetec.tms.app.filter.DefaultConsumerFilter.invoke(DefaultConsumerFilter.java:36)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboConsumerFilter.syncInvoke(SentinelDubboConsumerFilter.java:83)
	at com.alibaba.csp.sentinel.adapter.dubbo.SentinelDubboConsumerFilter.invoke(SentinelDubboConsumerFilter.java:67)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at io.opentelemetry.javaagent.shaded.instrumentation.apachedubbo.v2_7.TracingFilter.invoke(TracingFilter.java:56)
	at io.opentelemetry.javaagent.instrumentation.apachedubbo.v2_7.OpenTelemetryFilter.invoke(OpenTelemetryFilter.java:37)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:91)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:52)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at com.alibaba.csp.sentinel.adapter.dubbo.DubboAppContextFilter.invoke(DubboAppContextFilter.java:43)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:69)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:79)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:265)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:93)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.invoke(MigrationInvoker.java:170)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:96)
	at org.apache.dubbo.common.bytecode.proxy97.getComplainListByApp(proxy97.java)
	at com.sprucetec.tms.app.waybill.breakers.WaybillTmsIntegralBreakerInvokeServiceImpl.getComplainListByApp(WaybillTmsIntegralBreakerInvokeServiceImpl.java:51)
	at com.sprucetec.tms.app.waybill.breakers.WaybillTmsIntegralBreakerInvokeServiceImpl$$FastClassBySpringCGLIB$$b2745f44.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.sprucetec.stone.spring.breaker.BreakerAspect.invokeResourceWithSentinel(BreakerAspect.java:134)
	at jdk.internal.reflect.GeneratedMethodAccessor399.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.sprucetec.tms.app.waybill.breakers.WaybillTmsIntegralBreakerInvokeServiceImpl$$EnhancerBySpringCGLIB$$299643f.getComplainListByApp(<generated>)
	at com.sprucetec.tms.app.nonwaybill.complain.service.impl.ComplainAppServiceImpl.getComplainListByApp(ComplainAppServiceImpl.java:37)
	at org.apache.dubbo.common.bytecode.Wrapper217.invokeMethod(Wrapper217.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.sprucetec.tms.app.filter.AppVersionManageProviderFilter.invoke(AppVersionManageProviderFilter.java:45)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at com.sprucetec.tms.app.filter.DefaultProviderFilter.invoke(DefaultProviderFilter.java:52)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46)
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61)`

**Comment by AlbumenJ** [comment]
Can you please provide the error stack cause?

**Comment by qingkaiyan** [comment]
[dubbo-test.zip](https://github.com/user-attachments/files/16186471/dubbo-test.zip)
This demo will reproducing the issue

**Comment by qingkaiyan** [comment]
[dubbo-test.zip](https://github.com/user-attachments/files/16190215/dubbo-test.zip)
Modify Hessian2Output.java to resemble 3.2.13 and the error will go away

**Comment by AlbumenJ** [comment]
I have tested it.
hessian-lite 4.x -> hessian-lite 3.x not works
hessian-lite 4.x -> hessian-lite 4.x works

I think we should check if there is any different between 3.x and 4.x.

**Pull request closed without merging**
